// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Minimal Prisma config object for tooling. Avoid importing 'prisma/config'
// during Next.js build to prevent module resolution errors.
const prismaConfig = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["SQLITE_URL"],
  },
};

export default prismaConfig;
